### ISSUE TITLE
ビルドが失敗する

### ISSUE THREAD

**Issue by miya0001** [IMI-Tool-Project/imi-enrichment-address#1]
ビルドを試したのですが、`npm run download` コマンドで失敗してしまいます。
ソースを確認したのですが、以下の行の `$url` に代入される URL が 404 になっているようです。

https://github.com/IMI-Tool-Project/imi-enrichment-address/blob/master/tools/download.sh#L15

URL の例: http://nlftp.mlit.go.jp/isj/dls/data/12.0b/46000-12.0b.zip

**Comment by frogcat** [comment]
データの取得先の [位置参照情報](https://nlftp.mlit.go.jp/cgi-bin/isj/dls/_choose_method.cgi) ですが、先月サイトリニューアルがありました。ライセンス変更（独自利用規約から CC-BY4.0）はあったものの URL レイアウトは変更されていないようです。
リニューアル前は平成30年度データがダウンロード可能だったのですが、リニューアル後は「選択肢はあるもののデータがない」状態となっていて、ダウンロードできなくなっているのが直接の原因と思います。

位置参照情報は例年 6〜7月にデータ更新を行うことが多く、平成30年度データはメンテナンス中なのかもしれません。また、近々令和元年度データもリリースされるのではないかと思います。

とりあえずビルドを通すには @dkastl さんのパッチ（平成29年度データを使う） が有効かと思います。

**Comment by kzkski** [comment]
ご指摘の内容も含めまして、IMI-Tool-Project 管理下のレポジトリ全体について脆弱性の解消・ビルドエラーの解消・README.md の見直しを行いました。
本件については、位置参照情報サイトのリニューアルによって平成30年度版データが取得できないことが原因でしたが、
現行の README.md の手順に従って環境を構築いただければ、テストをパスすることを確認しております。
また、最新のコミットで、位置参照情報の任意のバージョンを指定してダウンロードができるように修正を加えましたので
参考にしていただければと思います。
なお、本レポジトリは2021年3月を持ちましてアーカイブに移行することになりました。
Contribute ありがとうございました。
