### ISSUE TITLE
このリポジトリだけでは imi-enrichment-address-2.0.0.tgz がどこにあるのかわからない

### ISSUE THREAD

**Issue by ahuglajbclajep** [IMI-Tool-Project/imi-enrichment-address#3]
他のコンポーネントもそうですが、「インストール」におけるコマンドを以下のように修正したほうがよいように思います。
参考: <https://docs.npmjs.com/cli/install>

```diff
- $ npm install imi-enrichment-address-2.0.0.tgz
+ $ npm install https://info.gbiz.go.jp/tools/imi_tools/resource/imi-enrichment-address/imi-enrichment-address-2.0.0.tgz
```

**Comment by kzkski** [comment]
ご指摘の内容も含めまして、IMI-Tool-Project 管理下のレポジトリ全体について脆弱性の解消・ビルドエラーの解消・README.md の見直しを行いました。
なお、本レポジトリは2021年3月を持ちましてアーカイブに移行することになりました。
Contribute ありがとうございました。
